modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/ochotonida/pumpkinlauncher/issues"
displayURL="https://minecraft.curseforge.com/projects/jack-o-launcher"
## logoFile=""
credits=""
authors="ochotonida"

[[mods]]
modId="jack_o_launcher"
version="1.14.4-1.2.1"
displayName="Jack-O'-Launcher"
updateJSONURL="https://raw.githubusercontent.com/ochotonida/pumpkinlauncher/1.14/update.json"
description='''Exploding jack-o'-lanterns and stuff'''

[[dependencies.jack_o_launcher]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jack_o_launcher]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"